### ISSUE TITLE
Feature Request - Certificate Request Timeout/Retries

### ISSUE THREAD

**Issue by keithmattix** [cert-manager/istio-csr#112]
By design, [cert-manager does NOT retry failed `CertificateRequest`s](https://cert-manager.io/docs/concepts/certificaterequest/):
> Whether issuance of the certificate signing request was successful or not, a retry of the issuance will not happen. It is the responsibility of some other controller to manage the logic and life cycle of CertificateRequests.

Furthermore, there is no timeout mechanism in place for CR's that stay in the "Pending" state for an unacceptable amount of time (often due to a transient or unrecoverable error communicating with the `Issuer`). I'd like to propose that both of these mechanisms be added to istio-csr. For systems with a low certificate lifetime (like a hardened service mesh), auto-retries are a big help in preventing network communication issues due to expired certs. I've got a couple of ideas around design, but I'd like to solicit feedback first.

**Comment by JoshVanL** [comment]
Hi @keithmattix, thanks for opening the issue :slightly_smiling_face: 

> Furthermore, there is no timeout mechanism in place for CR's that stay in the "Pending" state for an unacceptable amount of time (often due to a transient or unrecoverable error communicating with the Issuer).

So this first point sounds like bad behavior of the _issuer_ implementation. An Issuer shouldn't really be leaving a request in a Pending state if it knows that a request cannot be completed. The issuer itself should actually be marking itself as not ready. Which Issuer are you using which is showing this behavior? Either its readiness check needs to be updated to properly poll or discover whether certificates _are_ able to get signed, and/or it should be more aggressive at marking a request as failed after a shorter period of time.

> For systems with a low certificate lifetime (like a hardened service mesh), auto-retries are a big help in preventing network communication issues due to expired certs. I've got a couple of ideas around design, but I'd like to solicit feedback first.

To this point- outside of the istiod Certificate resource, istio-csr only creates CertificateRequests in response to a request from envoy.

```
enovy -> istio-csr -> CertificateRequest -> Issuer
```

istio-csr will hang on that CertificateRequest until the resource has reached a terminal state (Denied/Failed/Signed). The relevant response is then returned to envoy which will do with it what it wants.

We _could_ implement some kind of retry logic, however this only fixes the issue for istio-csr. We should instead implement a proper fix on the Issuer side, which can then be enjoyed by all consumers :slightly_smiling_face: 

Wdyt?

**Comment by keithmattix** [comment]
@JoshVanL Thanks for those clarifications! The issuer I'm using is the Vault issuer. I'm completely on board with retries and timeouts being features for the more general issuer interface; I like the idea of end-users having more control over certificate issuance.

**Comment by keithmattix** [comment]
My apologies, I'm looking back and realizing the issue I was running into was with the _root_ Istio certificate in the helm chart; not an intermediate certificate generated automatically with istio-csr.
