### ISSUE TITLE
What is minimum supported version of cert-manager itself for istio-csr extension?

### ISSUE THREAD

**Issue by smarunich** [cert-manager/istio-csr#115]
We have cert-manager v1.3.1, will be it supported with istio-csr v0.3?

**Comment by JoshVanL** [comment]
Hi @smarunich, v1.3.1 is fine (see [README.md](https://github.com/cert-manager/istio-csr#istio-csr)) but we always recommend keeping your cert-manager up to date! v1.3 is no longer supported as per https://cert-manager.io/docs/installation/supported-releases/

**Comment by smaruni-BRONGA** [comment]
thank you @JoshVanL, that answers my question.

**Comment by smarunich** [comment]
Thank you @JoshVanL for the prompt response, that answers my question!
