### ISSUE TITLE
The link for download manifest is broken

### ISSUE THREAD

**Issue by kambei** [cert-manager/istio-csr#119]
The command
`curl -sSL https://raw.githubusercontent.com/cert-manager/istio-csr/main/docs/istio-config-getting_started.yaml > istio-install-config.yaml`

generate a file with "404" content.

The link is broken.

**Comment by hawksight** [comment]
the `_` needs to be a `-`

```shell
curl -sSL https://raw.githubusercontent.com/cert-manager/istio-csr/main/docs/istio-config-getting-started.yaml > istio-install-config.yaml
```

I'll try to PR that to the docs soon.

**Comment by hawksight** [comment]
I think this can be closed as it's resolved in https://github.com/cert-manager/istio-csr/pull/121/files
