### ISSUE TITLE
Multi-cluster Private CA Root Cert , how do i identify the cluster identity on workloads . 

### ISSUE THREAD

**Issue by anannaya** [cert-manager/istio-csr#123]
Steps followed. 

1. helm_v3  install \
  cert-manager jetstack/cert-manager \
  --namespace istio-system \
  --set installCRDs=true
2. kubectl create secret tls root-ca-key-pair --cert=root-cert.pem --key=root-key.pem --n istio-system 
3. 
kubectl apply -n istio-system -f - <<EOF
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: root-ca-key-pair
  namespace: istio-system
spec:
  ca:
    secretName: root-ca-key-pair
EOF
4. helm_v3 upgrade install -n istio-system cert-manager-istio-csr jetstack/cert-manager-istio-csr \
  --set app.server.clusterID=anand-eks \
  --set app.certmanager.issuer.name=root-ca-key-pair \
  --set app.certmanager.preserveCertificateRequests=true \
  --set app.istio.revisions={1-12-1} \
  --set app.tls.certificateDNSNames={cert-manager-istio-csr.istio-system.svc} \
  --set app.logLevel=3

**Comment by anannaya** [comment]
Basically i am looking some cluster level identity on workloads 
```
 istioctl proxy-config secret nginx-55b5466f8c-km4gx -o json| jq '.dynamicActiveSecrets[0].secret.tlsCertificate.certificateChain.inlineBytes' | sed 's/"//g' | base64 --decode | openssl x509 -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            cc:2a:e3:f5:f3:ac:35:bc:24:1f:75:07:8a:bb:4a:b2
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = anand-istio-root-A-ca-ss
        Validity
            Not Before: Jan 20 07:30:52 2022 GMT
            Not After : Jan 20 08:30:52 2022 GMT
        Subject: O =
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:e4:c9:8d:54:31:35:2e:0f:c4:aa:c6:da:19:11:
                    0e:2c:b9:65:01:54:a5:cd:de:6f:a1:c4:03:b1:0e:

**Comment by JoshVanL** [comment]
Hi @anannaya. Some suggestions for encoding cluster information inside the workload identity certificate would be 1. a distinct trust domain for each cluster (`cluster-1.my-trust.domain`, `cluster-2.my-trust.domain`), or 2. Use distinct Issuer names (`Issuer: CN = foo-cluster-1`, `Issuer: CN = foo-cluster-2`)

**Comment by anannaya** [comment]
I have used 2 intermediate certs with different CN to overcome this. Thanks for help
