### ISSUE TITLE
Allow override of istiod-tls certificate common name in helm chert (for non-standard istiod deployments)

### ISSUE THREAD

**Issue by SpectralHiss** [cert-manager/istio-csr#132]
Hello

The current istio-csr helm chart deploys the `istiod-tls` serving certificate as a cert-manager `Certificate` object at installation,
As you can see in [link](https://github.com/cert-manager/istio-csr/blob/43131ddc7a9d13c86ff21a98b6c55e45c160fec5/deploy/charts/istio-csr/templates/certificate.yaml#L7), the common name is statically set to: `istiod.istio-system.svc`.

In certain installations like Openshift, this will not be the correct address for Istiod as the Redhat Service Mesh operator appends the revision name to the service name for Pilot.
If we could add a parameter to override this default it would be important for this use-case and perhaps other scenarios also.

**Comment by kuberkaul** [comment]
+!

**Comment by wallrj** [comment]
I think this has been addressed by adding additional DNS names for the Istio revisions, in:
 * https://github.com/cert-manager/istio-csr/pull/88
 * https://github.com/cert-manager/istio-csr/pull/355
 * https://github.com/cert-manager/istio-csr/pull/454
