### ISSUE TITLE
Issue while setup istio-CSR

### ISSUE THREAD

**Issue by shinderupesh** [cert-manager/istio-csr#175]
I am trying to setup [Istio-CSR](https://github.com/cert-manager/istio-csr/blob/v0.4.0/docs/getting_started.md). But getting following issue while deploying istio-CSR helm chart:

```
Command to setup from docs:
   helm install -n cert-manager cert-manager-istio-csr jetstack/cert-manager-istio-csr \
  --set "app.tls.rootCAFile=/var/run/secrets/istio-csr/ca.pem" \
  --set "volumeMounts[0].name=root-ca" \
  --set "volumeMounts[0].mountPath=/var/run/secrets/istio-csr" \
  --set "volumes[0].name=root-ca" \
  --set "volumes[0].secret.secretName=istio-root-ca"
```

`Error: template: cert-manager-istio-csr/templates/serviceaccount.yaml:3:7: executing "cert-manager-istio-csr/templates/serviceaccount.yaml" at <ne .Values.image.pullSecretName "">: error calling ne: incompatible types for comparison`

Details:
  Istio: v1.13.2
  cert-manager: v1.6.1
  helm: v3.5.2

Is there anything I missing?

**Comment by shinderupesh** [comment]
Looks like this issue is coming while deploying latest(0.5.0) helm chart of [cert-manager-istio-csr](https://artifacthub.io/packages/helm/cert-manager/cert-manager-istio-csr/0.5.0). If you use `cert-manager-istio-csr` of version v0.4.2 this issue is not coming. I don't exact reason of this failure in latest release. 

Is there any changes in deployment command?

Thanks

**Comment by JoshVanL** [comment]
Hi @shinderupesh, I think this might be a problem with Helm rather than the Chart.

I have been able to reproduce the error when using the same version as yourself (`v3.5.2`), however the error is not present when using at least `v3.8.2`. 

Can you update your helm installation to a higher version and test whether you get the same?

**Comment by shinderupesh** [comment]
Hi @JoshVanL, yes I am able to use Istio-CSR`(v0.5.0)` with Helm `v3.8.2`.

Thanks for the response.
