### ISSUE TITLE
CSR generation always defaults to P256 curve due to missing parameter

### ISSUE THREAD

**Issue by trc-ikeskin** [cert-manager/istio-csr#246]
We are currently using istio-csr in combination with a cert-manager Vault issuer. In Vault we configured the pki-roles to only allow ECDSA keys with 384-bit curves. As soons as istio-csr tries to sign CSRs using the Vault issuer it fails:

> 2024-01-22T10:53:30.030036Z    error    klog    failed to fetch initial serving certificate: failed to sign serving certificate: failed to wait for CertificateRequest istio-system/istio-csr-s7wf8 to be signed: created CertificateRequest has failed: [{Approved True
2024-01-22 10:53:29 +0000 UTC cert-manager.io Certificate request has been approved by cert-manager.io} {Ready False
2024-01-22 10:53:29 +0000 UTC Failed Vault failed to sign certificate: failed to sign certificate by vault: Error making API request. URL: POST https://xxxxxxxxxxxxxxxx/v1/pki_int/sign/xxxxxxxxxx 
Code: 400. Errors:  * role requires a minimum of a 384-bit key, but CSR's key is 256 bits}]: error running cert-manager-istio-csr

Quickly glancing at the code it seems that the `GenCSR` method of istios `pkiutil` 'expects' a parameter called `ECCCurve` and defaults to a 256-bit curve in case its not provided: https://github.com/istio/istio/blob/master/security/pkg/pki/util/generate_csr.go#L42 

Unfortunately in the `fetchCertificate` method the `opts` map lacks this option, it is neither derived from the `ServingCertificateKeySize` nor is it settable through a dedicated parameter: https://github.com/cert-manager/istio-csr/blob/e82df7e50b460e86668b78737a5db3a29891f13c/pkg/tls/tls.go#L288

Any chance this could implemented to allow the usage of ECDSA keys with a curve size larger than 256 bits?

**Comment by SpectralHiss** [comment]
Thanks for reporting this @trc-ikeskin! 
I don't see any reason not to do this and it should be a relatively straightforward fix.
I will raise a tentative PR to address this issue in the coming days.

**Comment by SpectralHiss** [comment]
I think the reason this was not initially supported is that on the release of Istio 1.6 where ECC was introduced, only P256 was supported, but I can see now that P384 + P256 are supported [currently](https://istio.io/latest/docs/ops/configuration/traffic-management/manage-mesh-certificates/#signature-algorithm)
This was introduced about 10 months ago in [this PR](https://github.com/istio/istio/pull/44459)

We will enable this key size option for both the Istiod cert and istio-csr's own server cert (which is the one your error comes from).
You'd still need to set the Istio installation configuration as show in the [documentation here](https://istio.io/latest/docs/ops/configuration/traffic-management/manage-mesh-certificates/#signature-algorithm) if you want all workload identities to use the same algorithm as we will not override the incoming CSRs.

**Comment by trc-ikeskin** [comment]
@SpectralHiss you are absolutely right. Shortly after opening this issue I found the PR myself. 
Thank you for the heads up and you work on this!

**Comment by SpectralHiss** [comment]
@trc-ikeskin try this now and see if it works, you can find an example helm chart + istio install [here](https://github.com/SpectralHiss/istio-csr/blob/1f1b9fb5aa4eaead96a5024e8224b5a48ef2e58f/test/ecc/values/istio-csr-ecdsa_p384.yaml#L30)
