### ISSUE TITLE
Minimum Required Kubernetes Version

### ISSUE THREAD

**Issue by nschhina** [cert-manager/istio-csr#32]
What's the minimum required Kubernetes Version to run this CSR service with Istio 1.8, I'm using Kubernetes 1.16 and running into issues with Istio sidecar not being able to get the CSR to istiod and see the following errors on the istio-proxy container 
`**unknown service istio.v1.auth.IstioCertificateService**`
`resource:default failed to generate secret for proxy: rpc error: code = Unimplemented desc = unknown service istio.v1.auth.IstioCertificateService`

As far as I know Istio provides integration with external CA for Kubernetes 1.18, but I want to make sure this works with 1.16

**Comment by JoshVanL** [comment]
Hi @nschhina, just to be clear, this is the integration of replacing the istiod as the CA server and replacing it with istio-csr. This is _not_ using the certificates.k8s.io CSR integration?

**Comment by nschhina** [comment]
@JoshVanL I understand. But do you know what's the minimum K8S version required for this to work? I successfully followed all the installation steps but istio sidecars are still not getting the certificate from cert manager istio csr

**Comment by JoshVanL** [comment]
It would be the same required minimal version of your istio and cert-manager installation. What is the status of the created CertificateRequests?

**Comment by SgtCoDFish** [comment]
This has been inactive for a while with no replies so I'll close. I think Josh's statement above is pretty clear (and is still true today I think):

> [The minimum required k8s version] would be the same required minimal version of your istio and cert-manager installation
