### ISSUE TITLE
Document Link Fixes

### ISSUE THREAD

**Issue by gkarthiks** [cert-manager/istio-csr#328]
The Document needs fix for various links in this page https://cert-manager.io/docs/usage/istio-csr/ with the new version/commits in the GH.

For example, the below links to the hack directory that is not available in the code base anymore in GH.

```
Why Custom Istio Install Manifests?
If you take a look at the contents of [the example Istio install manifests](https://github.com/cert-manager/istio-csr/tree/main/hack) there are a few custom configuration options which are important.
```

**Comment by inteon** [comment]
@gkarthiks the links should work now.
This was fixed in https://github.com/cert-manager/website/pull/1502
