### ISSUE TITLE
istio 1.9 support

### ISSUE THREAD

**Issue by tmshort** [cert-manager/istio-csr#33]
The README indicates that this only supports istio 1.7 and 1.8. What about 1.9 support?

**Comment by JoshVanL** [comment]
Hi @tmshort, I have just merged in the config which works with istio v1.9 and passes the tests https://github.com/cert-manager/istio-csr/blob/master/hack/istio-config-1.9.1.yaml

I have also updated the README.md to reflect this.

Let me know if I can help any further.
