### ISSUE TITLE
Modify schema validation to allow additional properties

### ISSUE THREAD

**Issue by volvera10** [cert-manager/istio-csr#391]
The issue seems to be due to the `additionalProperties`  being set to false in values.json.schema
https://github.com/cert-manager/istio-csr/blob/main/deploy/charts/istio-csr/values.schema.json#L4C8-L4C28

This results in not allowing additional properties being set in the values.

https://json-schema.org/understanding-json-schema/reference/object#additionalproperties
Note - Setting the additionalProperties schema to false means no additional properties will be allowed.
By having defined the additionalProperties setting to false in the chart, essentially telling Helm - or really any JSON schema validator that it's not allowed to have any additional properties defined besides those defined in their JSON schema.

Here is an example of what helm returns when we try and set an additional value:

```
Helm install failed for release cert-manager/csr with chart cert-manager-istio-csr@v0.10.0: values don't meet the specifications of the schema(s) in the following chart(s):
      cert-manager-istio-csr:
      - (root): Additional property domain is not allowed
      - (root): Additional property bigbang is not allowed
```

**Comment by inteon** [comment]
@volvera10 could you give an example of when this would be useful? What additional values do you want to set?

**Comment by inteon** [comment]
We intentionally set `additionalProperties: false` to prevent typos.

Please reopen the issue if you have an example of where adding an unknown field to values.yaml would be useful.
