### ISSUE TITLE
Installation into existing istio cluster

### ISSUE THREAD

**Issue by NickScottKortical** [cert-manager/istio-csr#43]
Hi, in the installation instructions it states: `Finally, install istio. Istio must be installed using the IstioOperator configuration changes within https://github.com/cert-manager/istio-csr/blob/master/hack/istio-config-1.8.2.yaml` This suggests that you would have installed all the previous crd's etc into a cluster without Istio running, is it possible to install this into a cluster that already has IstioOperator running? (The use case is in the instance of creating a GKE cluster with istio enabled, and then installing this once that cluster is running)

**Comment by JoshVanL** [comment]
Hi @NickScottKortical, currently the recommended method of installation is always to install istio _after_ istio-csr. The reason for this is that it will require a CA migration from the one which is created on boot, over to the istio-csr one. This is a tricky process to get right and is not fully supported by istio in an automated way https://blog.christianposta.com/diving-into-istio-1-6-certificate-rotation/. There is some work going on upstream to automate this process which should land in 2021 https://docs.google.com/spreadsheets/d/1FJ3AJFFnGw6TxZAoyj-zgFwTn37WsMKTOGNR4FjG7T8/edit#gid=117171340

If you are not worried about down time if the cluster has just been made, then it would be fine to install istio-csr, change the istio configuration, remove the selfsigned CA secrets from istio-system, and reboot all istio controlplane/workloads.

**Comment by NickScottKortical** [comment]
Great thanks for the detailed update. I have actually moved away from the GKE addon version of istio and am manually installing istio using istio operator after the cluster is created, so installing istio-csr before i do that step will work fine for me now. Thanks for the help!

**Comment by JoshVanL** [comment]
No problem! I'll close the issue out but please feel free to reopen if needed.

/close
