### ISSUE TITLE
Specifying a trust domain

### ISSUE THREAD

**Issue by janzantinge** [cert-manager/istio-csr#50]
I would like to deploy Istio CSR to a Istio cluster configured to use a specific trust domain (something other then `cluster.local`.

I poked around the Helm chart and the code to see if this was possible but I don't think it is. I've created a PR that I've built and deployed in my cluster which seems to do what I need.

**Environment details (remove if not applicable)**:
- Kubernetes version: 1.18
- Cloud-provider/provisioner: AWS EKS
- cert-manager version: 1.2.0
- Install method: Helm

/kind feature

**Comment by janzantinge** [comment]
The PR: https://github.com/cert-manager/istio-csr/pull/51

**Comment by JoshVanL** [comment]
Fixed via https://github.com/cert-manager/istio-csr/pull/51
/close
