### ISSUE TITLE
cert-manager-istio-csr:PSP Issues: Error: container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by VivekNidhi** [cert-manager/istio-csr#52]
We have slightly restricted cluster  with PSP and since we are using GitOps. I have exported the istio-csr [https://github.com/cert-manager/istio-csr]
The generated manifest : https://github.com/VivekNidhi/gitops-istio/blob/main/istio-csr-manifest.yaml, but when we bring up csr getting the below error. Is it possible to know the exact privileges required or any resolution for this. 

Error: 
Pulling image "XXXX/jetstack/cert-manager-istio-csr:v0.1.2" | Pulling | 17 May 2021, 16:08:30 | 17 May 2021, 16:13:37 | 25 | &nbsp;
-- | -- | -- | -- | -- | --
Error: container has runAsNonRoot and image will run as root

**Comment by JoshVanL** [comment]
Hi @VivekNidhi, I have opened up #54  which should fix this issue. Once merged, I will create a new release with this image.

If you have time, it would be great if you could try this image yourself to make sure it properly fixes your issue.
