### ISSUE TITLE
cert-manager-istio-csr pods lose readiness when new pods are being deployed.

### ISSUE THREAD

**Issue by neerajaustin** [cert-manager/istio-csr#56]
I have been noticing this behavior consistently when new pods are deployed with sidecars, I start seeing the istio-csr pod with 0/1 status. If you need more information, I can try to provide.

I am using Istio 1.9.2 with K8s 1.20

I see this error on the istio-csr pod logs.

E0521 19:48:39.995122       1 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cert-manager-istio-csr-658d97f5df-sjglt.16812cb7fb46fdf6", GenerateName:"", Namespace:"istio-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"istio-system", Name:"cert-manager-istio-csr-658d97f5df-sjglt", UID:"582a50bf-07bb-4fbc-a533-39e1725d06e1", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"24314978", FieldPath:""}, Reason:"LeaderElection", Message:"cert-manager-istio-csr-658d97f5df-sjglt_bd60581f-2123-4ea7-938a-1a0a6a007acb stopped leading", Source:v1.EventSource{Component:"cert-manager-istio-csr-658d97f5df-sjglt_bd60581f-2123-4ea7-938a-1a0a6a007acb", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc02221835ff9bbf6, ext:5169901101694, loc:(*time.Location)(0x277d240)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc02221835ff9bbf6, ext:5169901101694, loc:(*time.Location)(0x277d240)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'rpc error: code = Unknown desc = exec (try: 500): database is locked' (will not retry!)

**Comment by JoshVanL** [comment]
Should be fixed in #62 and is released in `v0.2`.
