### ISSUE TITLE
do the resources in cert-manager-bootstrap-resources.yaml need to go into the istio-system namespace?

### ISSUE THREAD

**Issue by travnewmatic** [cert-manager/istio-csr#57]
i was having problems with my cert-manager-istio-csr pod coming up.

should https://github.com/cert-manager/istio-csr/blob/master/hack/demo/cert-manager-bootstrap-resources.yaml be namespaced to `istio-system`?

`kubectl -n istio-system apply -f https://github.com/cert-manager/istio-csr/raw/master/hack/demo/cert-manager-bootstrap-resources.yaml` works for me

**Comment by JoshVanL** [comment]
Hi @travnewmatic, that's correct, they need to exist in the istio-system namespace. The CertificateRequests that are created by istio-csr are also in istio-system and so need to be able to reference the namespaced Issuer.

**Comment by JoshVanL** [comment]
Closing this issue.

Feel free to open if needed.

/close
