### ISSUE TITLE
Istio CSR certificate DNS names

### ISSUE THREAD

**Issue by janzantinge** [cert-manager/istio-csr#61]
I have a need to send istio-csr requests from "outside" the cluster. istio-csr is fronted by a load balancer and a route53 name. The certificate presented by istio-csr is only good for the internal (to the k8s cluster) name (`cert-manager-istio-csr.cert-manager.svc`).

I need to add a command line parameter that can allow me to set the dns-names that will be added to istion-csr's CSR ...

I've created a [PR](https://github.com/cert-manager/istio-csr/pull/60) that does this, LMK if this makes sense.

**Environment details**:

- Kubernetes version: 1.19
- Cloud-provider/provisioner: AWS EKS
- cert-manager version: 1.2.0
- Install method: Helm

/kind feature

**Comment by JoshVanL** [comment]
Fixed in #60 
Thanks again @janzantinge !
/close
