### ISSUE TITLE
using vault issuer expects common name from cert-manager-istio-csr when attempting to create server cert

### ISSUE THREAD

**Issue by jithkaringada-corp** [cert-manager/istio-csr#80]
When I attempt to run this command:
helm --kube-context minikube install -n cert-manager -f istio-csr-values.yaml cert-manager-istio-csr jetstack/cert-manager-istio-csr 

I get the following error:
error: failed to fetch initial serving certificate: failed to sign serving certificate: failed to wait for CertificateRequest cert-manager/istio-csr-hp5m5 to be signed: created CertificateRequest has failed: [{Approved True 2021-07-25 01:56:47 +0000 UTC cert-manager.io Certificate request has been approved by cert-manager.io} {Ready False 2021-07-25 01:56:47 +0000 UTC Failed Vault failed to sign certificate: failed to sign certificate by vault: Error making API request.

URL: POST https://vault.local:8200/v1/pki_int/sign/test-dot-com
Code: 400. Errors:

* the common_name field is required, or must be provided in a CSR with "use_csr_common_name" set to true, unless "require_cn" is set to false}]

istio-csr-values.yaml has this content:
replicaCount: 3
service: 
  port: 443
  type: NodePort
  nodePort: 30443
app:
  logLevel: 5
  certmanager:
    issuer:
      name: vault-istio-ca-issuer
      kind: Issuer
      group: cert-manager.io
    namespace: cert-manager
    preserveCertificateRequests: true
  tls: 
    trustDomain: yenzara.com
    certificateDuration: 20s
    certificateDNSNames:
    - cert-manager-istio-csr.cert-manager.svc
  server:
    maxCertificateDuration: 5m
    serving: 
      address: 0.0.0.0
      port: 6443
  controller:
    rootCAConfigMapName: istio-ca-root-cert
    leaderElectionNamespace: cert-manager
resources: {}

**Comment by jithkaringada-corp** [comment]
When I update the vault policy to have require_cn: false, then it works but I would like to use CN. How do I get the cert-manager-istio-csr to supply a common name when requesting for a certificate?

**Comment by JoshVanL** [comment]
Hi @jithkaringada-corp, common names are not used for istio certificates and instead make use of spiffe URIs, and DNS alt names for istiod's webhook. istio-csr similarly only uses DNS.

Whilst we _could_ change istio-csr to use a common name for its serving certificate, it is superfluous and you would have the same issue for istio's own certs.

What is the reason for the common name requirement?

**Comment by jithkaringada-corp** [comment]
@JoshVanL I am setting up my minikube instance with istio, and it seems like I would have run into issues with workload certs. I hadn't got that far as I spent a lot of time trying to figure out the CN thing. It looks like if you don't provide vault the specific configuration on the role to not require common names, it will default to requiring it. It may be worth noting and documenting for vault issuers. Thank you for the information. This was super helpful. Understanding that the CN is not needed is more than sufficient. We use the common name to do whitelisting in the company i work for, so it was just an expectation that common name would be supported, I don't really have a reason for needing it.

**Comment by JoshVanL** [comment]
Thanks @jithkaringada-corp, glad the issue has been fixed. I will mark this issue as closed with a mind on improving documentation for what kinds of policy istio certificates require.

Feel free to re-open if something else comes up.

/close
