### ISSUE TITLE
istiod certificate duration too short

### ISSUE THREAD

**Issue by bpotaczek** [cert-manager/istio-csr#81]
Using AWS PCA the minimum cert duration is 24h and the istiod certificate is hard coded to 1h in the chart. Can this be made configurable in the values.yaml file?

https://github.com/cert-manager/istio-csr/blob/master/deploy/charts/istio-csr/templates/certificate.yaml#L16

**Comment by JoshVanL** [comment]
Thanks for the issue @bpotaczek, that is indeed very annoying :smile: 

I will open a PR to make this value configurable and make a new Helm Chart version available.

/assign

**Comment by JoshVanL** [comment]
@bpotaczek The v0.2.1 Helm Chart is now available and this variable should be configurable using the value `app.tls.istiodCertificateDuration`. Please give it a go :smile:

**Comment by bpotaczek** [comment]
Thanks @JoshVanL, looks good. 

I forgot to add that AWS also requires a commonName set on the Certificate object but I can open a new issue for that. I had updated it a few weeks ago locally and forgot about it.
